document.writeln("<div id=\"footer\">");
document.writeln("	<div class=\"about\">");
document.writeln("		<dl>");
document.writeln("			<dt>关于</dt>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/aboutus.html\">关于我们</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/values.html\">我们的价值观</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/event.html\">大事记</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/copyright.html\">版权声明</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/ad.html\">广告服务</a></dd> ");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/contactus.html\">联系我们</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt>帮助</dt>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/help.html\">常见问题</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/sitemap.html\">网站地图</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/joinus.html\">加入我们</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/tougao.html\"><img src=\"http://img.lanrentuku.com/img/images/x.gif\" class=\"minihot\"/>网友投稿</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/links.php\">友情链接</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/guestbook.html\">在线留言</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt>收藏</dt>");
document.writeln("			 <dd><a onclick=\"addToFavorite()\">Ctrl+D收藏</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/shortcut.php\">放到桌面</a></dd>");
document.writeln("			 <dd><a href=\"http://www.lanrentuku.com/about/rssmap.html\">订阅rss</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt>关注</dt>");
document.writeln("			 <dd><a href=\"http://weibo.com/u/2556500765\" target=\"_blank\">新浪微博</a></dd>");
document.writeln("			 <dd><a href=\"http://t.qq.com/lanrentuku_com\" target=\"_blank\">腾讯微博</a></dd>");
document.writeln("			 <dd><a href=\"http://511401068.qzone.qq.com/\" target=\"_blank\">qq空间</a></dd>");
document.writeln("			 <dd><a href=\"http://huaban.com/lanrentuku\" target=\"_blank\">花瓣</a></dd>");
document.writeln("			 <dd><a href=\"http://lanrentuku.lofter.com\" target=\"_blank\">懒人博客</a></dd>");
document.writeln("			 <dd><a href=\"http://koubei.baidu.com/s/lanrentuku.com\" target=\"_blank\">百度口碑</a></dd>");
document.writeln("		</dl>");
document.writeln("    </div>");
document.writeln("	<div class=\"jinbu\">");
document.writeln("		<dl>");
document.writeln("			<dt>我们一直在进步</dt>");
document.writeln("		     <script>dy(\"jinbu\");</script>");
document.writeln("		</dl>");
document.writeln("    </div>");
document.writeln("	<span class=\"copyright\">Copyright (C) 2006-2017 <a href=\"http://www.lanrentuku.com/\">lanrentuku.com</a> All Rights Reserved. Powered by <a href=\"http://www.dedecms.com/\">DedeCMS_V57</a></span>");
document.writeln("	<span class=\"beian\"><a href=\"http://www.miibeian.gov.cn/\">京ICP备08001501号</a><a name=\"gobottom\"> </a></span>");
document.writeln("</div>");
document.writeln("<a title=\"返回顶部\" class=\"top\" href=\"#\"></a>");