document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <style>");
document.writeln("        body{");
document.writeln("            margin: 0px;");
document.writeln("            padding: 0px;");
document.writeln("        }");
document.writeln("        iframe{");
document.writeln("            width:320px;");
document.writeln("            height:50px;");
document.writeln("            margin-left:20px;");
document.writeln("            background:rgba(0, 114, 114, 0.42);");
document.writeln("        }");
document.writeln("        #div1{");
document.writeln("            width:100%;");
document.writeln("            background: rgb(209, 114, 114);");
document.writeln("            height:150px;word-wrap:break-word");
document.writeln("        }");
document.writeln("        #div2{");
document.writeln("            width:100%;");
document.writeln("            background: rgb(124, 204, 93);");
document.writeln("            height:850px;");
document.writeln("        }");
document.writeln("        #div3{");
document.writeln("            width:100%;");
document.writeln("            background: rgb(93, 178, 204);");
document.writeln("            height:300px;");
document.writeln("        }");
document.writeln("        #div4{");
document.writeln("            width:100%;");
document.writeln("            background: rgb(110, 93, 204);");
document.writeln("            height:600px;");
document.writeln("        }");
document.writeln("        #div5{");
document.writeln("            width:100%;");
document.writeln("            background: rgb(187, 93, 204);");
document.writeln("            height:100px;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div id=\'div1\'></div>");
document.writeln("    <iframe src=\'./ins.html\' frameborder=\'0\' id=\'on1\'  scrolling =\'no \'></iframe>");
document.writeln("    <div id=\'div2\'></div>");
document.writeln("    <iframe src=\'./ins.html\' frameborder=\'0\' id=\'on2\'  scrolling =\'no \'></iframe>");
document.writeln("    <div id=\'div3\'></div>");
document.writeln("    <div id=\'div4\'></div>");
document.writeln("    <iframe src=\'./ins.html\' frameborder=\'0\' id=\'on3\'  scrolling =\'no \'></iframe>");
document.writeln("    <div id=\'div5\'></div>");
document.writeln("</body>");
document.writeln("</html>");